spring.application.name=demo
JWT_SECRET=supersecret123

spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=27062006

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresSQLDialect
spring.jpa.hibernate.ddl-auto=create
#or update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.docker.compose.enabled=false
