version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 27062006
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    networks:
      - app-network

  auth-api:
    build: ./auth-api
    container_name: auth-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 27062006
      INTERNAL_TOKEN: shared-secret
      DATA_API_URL: http://data-api:8081/api/transform
    depends_on:
      - postgres
      - data-api
    networks:
      - app-network

  data-api:
    build: ./data-api
    container_name: data-api
    ports:
      - "8081:8081"
    environment:
      INTERNAL_TOKEN: shared-secret
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
